### ISSUE TITLE
Installation Error - Failed to enable unit: File snipsledcontrol.service: Invalid argument

### ISSUE THREAD

**Issue by collinshubKiwi** [Psychokiller1888/snipsLedControl#31]
**Do not remove fields, answer them, otherwise your bug will be reported as invalid and closed**

**How I did start SLC, with what arguments**
python main.py xxxxxxxxx
Did not get this far as failed to install.

**Led device name**
The name of the device such as "ReSpeaker 2" or "Matrix Voice"
Matrix Creator

**The bug**
Do you need to install / configure your matrixcreator? This is strongly suggested as it does turn off services that might conflict as well!
1) yes
2) no
3) cancel
#? 1
######################### Please run this script with sudo ##########################
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2203  100  2203    0     0   4109      0 --:--:-- --:--:-- --:--:--  4110
OK
deb https://apt.matrix.one/raspbian stretch main
deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./
--2019-02-09 18:12:56--  https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2620:113:80c0:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1080 (1.1K)
Saving to: ‘STDOUT’

-                                  100%[===============================================================>]   1.05K  --.-KB/s    in 0s

2019-02-09 18:12:58 (14.4 MB/s) - written to stdout [1080/1080]

key 62EB1A0917280DDF:
1 signature not checked due to a missing key
OK
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Ign:2 http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0 ./ InRelease
Hit:3 https://apt.matrix.one/raspbian stretch InRelease
Get:4 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Hit:5 http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0 ./ Release
Hit:6 https://raspbian.snips.ai/stretch stable InRelease
Fetched 15.0 kB in 2s (6,037 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
python-dev is already the newest version (2.7.13-2).
matrixio-malos is already the newest version (0.3.5).
The following packages were automatically installed and are no longer required:
  libmatrixio-malos-dev libmatrixio-protos-dev libopus0 matrixio-pocketsphinx matrixio-sphinxbase
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already satisfied: appdirs in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: backports-abc in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: matrix_io-proto in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: protobuf>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from matrix_io-proto)
Requirement already satisfied: six>=1.9 in /usr/lib/python2.7/dist-packages (from protobuf>=3.6.0->matrix_io-proto)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf>=3.6.0->matrix_io-proto)
Requirement already satisfied: packaging in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from packaging)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python2.7/dist-packages (from packaging)
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.9 in /usr/lib/python2.7/dist-packages (from protobuf)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyzmq in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: zmq in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyzmq in /usr/local/lib/python2.7/dist-packages (from zmq)
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from singledispatch)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages
Requirement already satisfied: tornado in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: backports_abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado)
Requirement already satisfied: futures in /usr/local/lib/python2.7/dist-packages (from tornado)
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from singledispatch->tornado)
##################### Enjoy! Psycho #######################
Failed to enable unit: File snipsledcontrol.service: Invalid argument
Failed to start snipsledcontrol.service: Unit snipsledcontrol.service is not loaded properly: Bad message.
See system logs and 'systemctl status snipsledcontrol.service' for details.
Finished installing Snips Led Control v1.7.1
You may want to copy over your custom led patterns to the new version

**Debug output**
Follow instructions on https://github.com/Psychokiller1888/snipsLedControl/wiki/Run-in-debug-mode
And paste the output

Failed to stop snipsledcontrol.service: Unit snipsledcontrol.service not loaded.
pi@snips:~/snipsLedControl_v1.7.1 $ sudo chown -R pi logs
pi@snips:~/snipsLedControl_v1.7.1 $ python main.py --debug=True
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    handler = logging.FileHandler(filename='logs.log', mode='w')
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/pi/snipsLedControl_v1.7.1/logs.log'

**To Reproduce**
Steps to reproduce the behavior
Tried 3 times to install without success. Any help much appreciated.

**Comment by collinshubKiwi** [comment]
Was able to get past the install issue. But still get a single led on and the shutdown takes awhile. Can get the google pattern to work. Look forward to the next release.
